version: 2

sources:
  - name: crypto_raw
    database: crypto-pipeline-2025
    schema: crypto_raw
    tables:
      - name: top_cryptos_raw
        columns:
          - name: id
            tests:
              - not_null
          - name: current_price
            tests:
              - not_null 